apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: iap-config
  namespace: airbyte
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: iap-oauth-credentials

