name: Deploy to Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'helm/**'
      - 'ingress/**'
      - '.github/workflows/deploy-staging.yml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Connectors Platform to Staging
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/828187884021/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'github-actions-staging@airbyte-backend-staging.iam.gserviceaccount.com'
      
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          install_components: 'gke-gcloud-auth-plugin'
      
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials airbyte-stage-gke \
            --region europe-west6 \
            --project airbyte-backend-staging
      
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'
      
      - name: Add Airbyte Helm repo
        run: |
          helm repo add airbyte https://airbytehq.github.io/helm-charts
          helm repo update
      
      - name: Create Kubernetes namespace and service account
        run: |
          kubectl create namespace airbyte --dry-run=client -o yaml | kubectl apply --validate=false -f -
          kubectl create serviceaccount airbyte-admin -n airbyte --dry-run=client -o yaml | kubectl apply --validate=false -f -
          kubectl annotate serviceaccount airbyte-admin -n airbyte \
            iam.gke.io/gcp-service-account=airbyte-stage-airbyte-sa@airbyte-backend-staging.iam.gserviceaccount.com \
            --overwrite
      
      - name: Deploy Airbyte with Helm
        run: |
          helm upgrade --install airbyte airbyte/airbyte \
            --version 0.49.24 \
            -n airbyte \
            -f helm/values-stage-ultra-minimal.yaml \
            --wait \
            --timeout 15m
      
      - name: Apply Ingress
        run: |
          kubectl apply --validate=false -f ingress/dual-domain-ingress.yaml
      
      - name: Wait for deployments
        run: |
          kubectl rollout status deployment/airbyte-server -n airbyte --timeout=5m || true
          kubectl rollout status deployment/airbyte-webapp -n airbyte --timeout=5m || true
          kubectl rollout status deployment/airbyte-worker -n airbyte --timeout=5m || true
      
      - name: Deployment status
        run: |
          echo "=== Pods ==="
          kubectl get pods -n airbyte
          echo ""
          echo "=== Services ==="
          kubectl get svc -n airbyte
          echo ""
          echo "=== Ingress ==="
          kubectl get ingress -n airbyte
          echo ""
          echo "=== SSL Certificates ==="
          kubectl get managedcertificate -n airbyte
      
      - name: Summary
        run: |
          echo "✅ Connectors Platform deployed to Staging!"
          echo ""
          echo "🌐 URLs:"
          echo "  Platform UI: https://connectors-staging.aitronos.com"
          echo "  API Endpoint: https://connectors-api-staging.aitronos.com"
          echo "  Direct IP: http://34.96.91.157"
          echo ""
          echo "⏱️  SSL certificates may take 15-60 minutes to provision"

