name: Deploy Frontend

on:
  push:
    branches:
      - main
      - stage
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'stage'
        type: choice
        options:
          - stage
          - production

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'stage' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Checkout Airbyte Platform
        uses: actions/checkout@v4
        with:
          repository: airbytehq/airbyte-platform
          path: airbyte-platform
          ref: main
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.19.0'
      
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
      
      - name: Install dependencies
        working-directory: airbyte-platform/airbyte-webapp
        run: pnpm install --engine-strict=false
      
      - name: Build frontend
        working-directory: airbyte-platform/airbyte-webapp
        env:
          NODE_ENV: production
        run: pnpm build --mode ${{ github.ref == 'refs/heads/main' && 'production' || 'local' }}
      
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          projectId: airbyte-backend-staging
          channelId: live
          target: ${{ github.ref == 'refs/heads/main' && 'production' || 'stage' }}

