name: Deploy Connectors Platform Backend

on:
  push:
    branches:
      - staging    # Auto-deploy staging
      - main       # Auto-deploy production
    paths:
      - 'helm/**'
      - 'ingress/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'staging') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/staging')
    
    environment:
      name: staging
      url: https://connectors-stage.aitronos.com
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials airbyte-stage-gke \
            --region europe-west6 \
            --project airbyte-backend-staging
      
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'
      
      - name: Add Airbyte Helm repo
        run: |
          helm repo add airbyte https://airbytehq.github.io/helm-charts
          helm repo update
      
      - name: Create/Update Kubernetes resources
        run: |
          # Ensure namespace exists
          kubectl create namespace airbyte --dry-run=client -o yaml | kubectl apply -f -
          
          # Ensure service account exists
          kubectl create serviceaccount airbyte-admin -n airbyte --dry-run=client -o yaml | kubectl apply -f -
          
          # Annotate service account for Workload Identity
          kubectl annotate serviceaccount airbyte-admin -n airbyte \
            iam.gke.io/gcp-service-account=airbyte-stage-airbyte-sa@airbyte-backend-staging.iam.gserviceaccount.com \
            --overwrite
      
      - name: Deploy Connectors Platform with Helm
        run: |
          helm upgrade --install airbyte airbyte/airbyte \
            --version 0.49.24 \
            -n airbyte \
            -f helm/values-stage-ultra-minimal.yaml \
            --wait \
            --timeout 15m
      
      - name: Apply Ingress
        run: |
          kubectl apply -f ingress/dual-domain-ingress.yaml
      
      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/airbyte-server -n airbyte --timeout=5m || true
          kubectl rollout status deployment/airbyte-webapp -n airbyte --timeout=5m || true
          kubectl rollout status deployment/airbyte-worker -n airbyte --timeout=5m || true
      
      - name: Verify deployment
        run: |
          echo "=== Pods ==="
          kubectl get pods -n airbyte
          echo ""
          echo "=== Services ==="
          kubectl get svc -n airbyte
          echo ""
          echo "=== Ingress ==="
          kubectl get ingress -n airbyte
          echo ""
          echo "=== SSL Certificates ==="
          kubectl get managedcertificate -n airbyte
      
      - name: Deployment Summary
        run: |
          echo "✅ Connectors Platform deployed to Staging!"
          echo ""
          echo "🌐 URLs:"
          echo "  Platform UI: https://connectors-stage.aitronos.com"
          echo "  API Endpoint: https://connectors-api-stage.aitronos.com"
          echo ""
          echo "⏱️  SSL certificates may take 15-60 minutes to provision"

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production') ||
      (github.event_name == 'push' && github.ref == 'refs/heads/main')
    
    environment:
      name: production
      url: https://connectors.aitronos.com
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_PROD }}
      
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      
      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials airbyte-prod-gke \
            --region europe-west6 \
            --project airbyte-backend-production
      
      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.13.0'
      
      - name: Add Airbyte Helm repo
        run: |
          helm repo add airbyte https://airbytehq.github.io/helm-charts
          helm repo update
      
      - name: Create/Update Kubernetes resources
        run: |
          # Ensure namespace exists
          kubectl create namespace airbyte --dry-run=client -o yaml | kubectl apply -f -
          
          # Ensure service account exists
          kubectl create serviceaccount airbyte-admin -n airbyte --dry-run=client -o yaml | kubectl apply -f -
          
          # Annotate service account for Workload Identity
          kubectl annotate serviceaccount airbyte-admin -n airbyte \
            iam.gke.io/gcp-service-account=airbyte-prod-airbyte-sa@airbyte-backend-production.iam.gserviceaccount.com \
            --overwrite
      
      - name: Deploy Connectors Platform with Helm
        run: |
          helm upgrade --install airbyte airbyte/airbyte \
            --version 0.49.24 \
            -n airbyte \
            -f helm/values-prod-minimal.yaml \
            --wait \
            --timeout 15m
      
      - name: Apply Production Ingress
        run: |
          kubectl apply -f ingress/production-ingress.yaml
      
      - name: Wait for deployment
        run: |
          kubectl rollout status deployment/airbyte-server -n airbyte --timeout=10m
          kubectl rollout status deployment/airbyte-webapp -n airbyte --timeout=10m
          kubectl rollout status deployment/airbyte-worker -n airbyte --timeout=10m
      
      - name: Verify deployment
        run: |
          echo "=== Pods ==="
          kubectl get pods -n airbyte
          echo ""
          echo "=== Services ==="
          kubectl get svc -n airbyte
          echo ""
          echo "=== Ingress ==="
          kubectl get ingress -n airbyte
          echo ""
          echo "=== SSL Certificates ==="
          kubectl get managedcertificate -n airbyte
      
      - name: Run Smoke Tests
        run: |
          echo "⏳ Waiting for ingress to be ready..."
          sleep 30
          
          # Test API health (add actual health check when available)
          echo "🧪 Running smoke tests..."
          # curl -f https://connectors-api.aitronos.com/api/v1/health || echo "Health check not yet available"
      
      - name: Deployment Summary
        run: |
          echo "✅ Connectors Platform deployed to Production!"
          echo ""
          echo "🌐 URLs:"
          echo "  Platform UI: https://connectors.aitronos.com"
          echo "  API Endpoint: https://connectors-api.aitronos.com"

